create table personalinfo (
    last_name       varchar2(32)not null,
    first_name      varchar2(64)not null,
    middle_name     varchar(32)not null,
    position_rc     varchar2(64),
    date_employed   varchar2(16),
    present_address varchar(64),
    pst_contact     number(16),
    province_address varchar2(54),
    pvc_contact     number(16),
    date_of_birth   varchar2(16),
    place_of_birth  varchar2(64),
    sex             varchar(8),
    civil_status    varchar2(16),
    citizenship     varchar2(16),
    religion        varchar2(16),
    height_cm       number(4),
    weight_kg       number(4),
    email_address   varchar2(16),
    sss_number      number(32),
    tin_number      number(32),
    pagibig_number  number(32),
    primary key (tin_number));
    
create table fambg (
    employee_id     number(16)not null,
    tin_number      number(32)not null,
    father_name     varchar2(64),
    father_address  varchar2(64),
    father_occupation varchar2(32),
    mother_name     varchar2(62),
    mother_address  varchar2(64),
    mother_occupation varchar2(32),
    spouse_name     varchar2(64),
    spouse_occupation varchar2(32),
    company_or_employer varchar2(32),
    number_of_children number(4),
    children_name       varchar2(64),
    children_age        number(4),
    emergency_contact   number(16),
    person_relationship varchar2(16),
    emergency_address   varchar(16),
    emergency_number    number(16),
    primary key (employee_id),
    foreign key (tin_number) references personalinfo );
    
create table applicants (
    applicant_number    number(16),
    tin_number          number(32),
    personality_test    varchar2(4),
    names_friends_relatives_employed    varchar2(256),
    salary_expected     number(16),
    primary key (applicant_number),
    foreign key (tin_number) references personalinfo);
    
create table schoolinfo (
    s_info_number       number(16)not null,
    tin_number          number(32)not null,
    elementary_graduated varchar2(64),
    year_graduated      number(8),
    highschool_graduated    varchar2(64),
    vocational          varchar2(64),
    year_earned         number(8),
    primary key (s_info_number),
    foreign key (tin_number)  references personalinfo);
    
create table eligibility (
    examination_number  number(16)not null,
    tin_number          number(32)not null,
    exam_taken_passed   varchar2(256),
    ratings             number(4),
    date_passed         varchar2(8),
    primary key (examination_number),
    foreign key (tin_number) references personalinfo);
    
create table careerprofile (
    career_profile_id       number(16)not null,
    tin_number              number(32)not null,
    company_school_name     varchar2(256),
    inclusive_dates         varchar2(32),
    last_position_held      varchar2(32),
    type_t_nt               varchar2(4),
    teaching_specify_level  varchar2(32),
    main_task_brief         varchar2(32),
    primary key (career_profile_id),
    foreign key (tin_number) references personalinfo);
    
create table acadcontri (
    contribution_number     number(32)not null,
    tin_number              number(32)not null,
    publication             varchar2(64),
    completed_researches    varchar2(256),
    recognition_awards      varchar2(256),
    fellowships_grants      varchar2(256),
    extension_acts          varchar2(256),
    primary key (contribution_number), 
    foreign key (tin_number) references personalinfo);

create table profaffiliate (
    affiliate_number        number(32)not null,
    tin_number              number(32)not null,
    name_of_org             varchar2(64),
    positions               varchar2(256),
    inclusive_dates         varchar2(256),
    primary key (affiliate_number),
    foreign key (tin_number) references personalinfo);
    
create table trainingrecord (
    training_number         number(32)not null,
    tin_number              number(32)not null,
    training_title          varchar2(64),
    no_of_hours             number(4),
    inclusive_dates         varchar2(64),
    sponsor_company         varchar2(64),
    primary key (training_number),
    foreign key (tin_number) references personalinfo);
    
create table medicalrecords (
    medical_rec_number      number(32)not null,
    tin_number              number(32)not null,
    last_physical_date      varchar2(32),
    purpose                 varchar2(32),
    results                 varchar2(32),
    dizziness               varchar2(4),
    fainting                varchar2(4),
    convulsion              varchar2(4),
    epilepsy                varchar2(4),
    paralysis               varchar2(4),    
    stroke                  varchar2(4),
    mental_disorder         varchar2(4),
    nervous_disorder        varchar2(4),
    chest_pain              varchar2(4),
    palpitation             varchar2(4),
    high_blood_pressure     varchar2(4),
    rheumatic_fever         varchar2(4),
    heart_murmur            varchar2(4),
    heart_attack            varchar2(4),
    asthma                  varchar2(4),
    hear_ailment            varchar2(4),
    tuberculosis            varchar2(4),
    diabetis                varchar2(4),
    allergy                 varchar2(4),
    hepatitis               varchar2(4),
    thyroid_disorder        varchar2(4),
    cancer                  varchar2(4),
    hypertension            varchar2(4),
    undergone_surgical_treatment varchar2(4),
    under_medical_observation varchar2(4),
    taking_medical_treatment varchar2(4),
    taking_psychiatric_treatment varchar2(4),
    pregnant                varchar2(4),
    if_yes_how_many_months  varchar2(4),
    abnormal_menstruation   varchar2(4),
    been_pregnant           varchar2(4),
    childbirth              varchar2(4),
    disorder_in_female_organs    varchar2(4),
    disorder_in_breasts     varchar2(4),
    primary key (medical_rec_number),
    foreign key (tin_number) references personalinfo );
    
create table legalprofile (
    legal_profile_number    number(32)not null,
    tin_number              number(32)not null,
    convicted_violation     varchar2(4),
    convicted_breach_infraction varchar2(4),
    yes_give_particular     varchar2(256),
    pending_cases           varchar(4),
    yes_give_details        varchar2(256),
    primary key (legal_profile_number),
    foreign key(tin_number) references personalinfo);

create table charref (
    applicant_number        number(32)not null,
    tin_number              number(32)not null,
    name_1                  varchar2(64),
    contact_number_1        number(16),
    occupation_1            varchar2(32),
    name_2                  varchar2(64),
    contact_number_2        number(16),
    occupation_2            varchar2(32),
    name_3                  varchar2(64),
    contact_number_3        number(16),
    occupation_3            varchar2(32),
    primary key (applicant_number),
    foreign key ( tin_number) references personalinfo); 